---
- name: Copy /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
- name: Copy hosts.allow
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    mode: 0644
    owner: root
    group: root
- name: Copy hosts.deny
  copy:
    src: hosts.deny
    dest: /etc/hosts.deny
    mode: 0644
    owner: root
    group: root
- name: Copy sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
