---
- include: assets.yml
  become: true
  tags: assets
- include: yum.yml
  become: true
- include: vmware.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  become: true
  tags:
  - vmware
- include: services.yml
  become: true
