---
- include: assets.yml
  sudo: yes
  tags: assets
- include: yum.yml
  sudo: yes
- include: vmware.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - vmware
- include: services.yml
  sudo: yes
